# Generated by Django 5.0.2 on 2024-02-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_agreement_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='agreement_end_date',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='monthly_rent_date',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='property',
        ),
    ]
