# Generated by Django 5.0.2 on 2024-02-06 19:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_remove_property_prices_property_rate_1bhk_and_more'),
        ('tenants', '0003_remove_tenant_agreement_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agreement_end_date', models.DateField(default=datetime.datetime(2025, 2, 6, 0, 51, 2, 615064))),
                ('monthly_rent_date', models.PositiveIntegerField()),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
    ]
