# Generated by Django 5.0.2 on 2024-02-06 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantunit',
            name='agreement_end_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 6, 0, 57, 16, 309422)),
        ),
    ]
