# Generated by Django 5.0.2 on 2024-02-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_tenant_unit_lease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='property',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='Lease',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
