# Generated by Django 5.0.2 on 2024-02-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_lease_tenant_remove_lease_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
