# Generated by Django 5.0.2 on 2024-02-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_property_features_alter_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
