# Generated by Django 5.0.2 on 2024-02-06 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_property_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_1bhk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_2bhk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_3bhk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_4bhk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
