# Generated by Django 5.0.2 on 2024-02-06 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_property_location_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='prices',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_prices', to='property.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rate_1bhk',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='rate_2bhk',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='rate_3bhk',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='rate_4bhk',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
