# Generated by Django 5.0.2 on 2024-02-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_remove_unit_property_property_prices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='prices',
        ),
        migrations.AddField(
            model_name='property',
            name='rate_1bhk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rate_2bhk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rate_3bhk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rate_4bhk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
